In [40]:
import pandas as pd

# โหลดข้อมูลจากไฟล์
file_path_1 = 'data/origin_migrations_UR.csv'
data_1 = pd.read_csv(file_path_1)

# ตรวจสอบค่าที่ไม่ซ้ำในคอลัมน์ 'loc1' จาก data_1
unique_loc1 = data_1['loc1'].unique()
print("ค่าที่ไม่ซ้ำในคอลัมน์ 'loc1' จาก data_1:")
for loc in unique_loc1:
    print(loc)

ค่าที่ไม่ซ้ำในคอลัมน์ 'loc1' จาก data_1:
Kisii
Kisumu
Machakos
Uvira
Siaya
Bukavu
Busia
Kakamega
Migori
Minembwe
Bujumbura
Embu
Homa Bay
Kitui
Nakuru
Kampala
Makueni
Nyamira
Arusha
Awendo
Bungoma
Eldoret
Kerugoya
Kiambu
Kinangop
Kitale
Meru
Mombasa
Mumias
Murang'A
Nairobi
Namaingo
Addis Ababa
Al Diyum East
Al Riyadh
Aweil
Bisoro
Bombolulu
Bondo
Bulambuli
Bumala
Ekalakala
Enugu
Fizi
Funyula
Gbarnga
Gisambai
Gitega
Githunguri
Goma
Gucha
Juba
Kangema
Kapsabet
Karatina
Katanga
Kericho
Keroka
Khartoum
Kigoma
Kilome
Kimilili
Kinamba
Kinshasa
Kisauni
Kuajok
Kyua
Lagos
Lwanda
Makal
Makindu
Malaba
Masii
Maua
Mekanisa
Moyale
Muranga
Mwanza
Mwingi
Naivasha
Ngaramtoni
Ngozi
Nyeri
Ogembo
Ol Kalou
Oyugis
Pumwani
Rabuor
Rafiki
Rongo
Sagana
Siaya Town
Sondu
Soweto
Taita Taveta
Thika
Tororo
Villa
Wote
nan
Johannesburg
Bulawayo
Thohoyandou
Maputo
Durban
Harare
Polokwane
 Fourways
Germiston
Louis Trichardt
Makhado
Pretoria
Tzaneen
Alberton
Brits
Kwekwe
Lubumbashi
Lusaka
Maseru
Nelspruit
Angola
Awasa
Bandal
Bangou
Beila
Bergville
Bilene
Blairgowrie
Blantyre
Bloemfontein
Bushbuckridge
Chokwe
Dennilton
Dutywa
Elim
Embangweni
Ermelo
Fort Beaufort
Gaborone
Gomora
Hazyview
Karonga
Katlehong
Khongoloti
Klerksdorp
Kranskop
Kwamhlanga
Lahore
Leribe
Lohagora
Luanda
Lubango
Madadeni
Mafeteng
Mafikeng
Makiso
Malvern
Mamelodi
Mannies
Mbuji-Mayi
Mokopane
Mondlo
Morogoro
Mozambique
Mulanje
Mzilikazi
Mzuzu
Nancefield
New Castle
Nkandla
Nomlatu
Nqutu
Nyembani
Paris
Piet Retief
Pietersburg
Plateau
Plumtree
Port Elizabeth
Qwaqwa
Randfontein
Rustenburg
Sandton
Selebi-Phikwe
Shikhupora
Springs
Tabankulu
Tema
Thaba Tseka
Thulamahashe
Tsholotsho
Ubundu
Victoria Falls
Witbank
Workshop
Xai Xai
Xai-Xai
Zaza
Tamale
Lome
Niamey
Bolgatanga
Takoradi
Accra
Akim Oda
Koforidua
Madina
Gushiegu
Ho
Kpandai
Aflao
Agadez
Cape Coast
Ilorin
Kpando
Kpassa
Kumasi
Somanya
Techiman
Wa
Yendi
Aba
Abaji
Abakaliki
Abeokuta
Abuja
Abujuro
Adawlato
Adenta
Agbani
Agbara
Agbor
Alakple
Amawom
Anambra
Anyinam
Ariaria
Asante Camp No.1
Ashanti Mampong
Atonsu
Avepozo
Bamako
Banfora
Bawah Barracks
Benin City
Bimbilla
Bunso
Calabar
Cocody
Delta
Diffa
Dosso
Ebonyi
Ebute Metta
Ejigbo
Gbagemey
Hohoe
Ikeja
Ikotun
Kamina
Keta
Kete Krachi
Kpangalam
La
Lawra
Lewis Face One
Makola
Mamfe
Maradi
Mile 15
Millionaire
Miri
Mopti
Mpraeso
New Karu
Nima
Nkwanta
Nnewi
Nsawam
Ocansey Junction
Oda
Odumase
Ogunu
Ohaukwu
Ojo
Old Fadama
Onitsha
Ouagadougou
Owerri
Port Harcourt
Saltpond
Sogakope
Sokode
Suhum
Surulere
Tanoso
Techaoudjo
Teshie
Water Bolt~ Polosa Street
Winneba
Wulensi
Yamfo
Yantala
Zinder
Zogbedji

In [41]:
import pandas as pd

# โหลดข้อมูลจากไฟล์
file_path_1 = 'data/level1_migrations_UR.csv'
file_path_2 = 'data/star_all_distances.csv'
data_1 = pd.read_csv(file_path_1)
data_2 = pd.read_csv(file_path_2)

# สร้าง DataFrame ที่ใช้ location_l และ neighborhood_9 จาก data_2
location_neighborhood_df = data_2[['location_l', 'neighborhood_9']].drop_duplicates().reset_index(drop=True)

# ตรวจสอบคู่ที่ไม่ซ้ำเพื่อความถูกต้อง
print("คู่ที่ไม่ซ้ำของ location_l และ neighborhood_9 จาก data_2:")
print(location_neighborhood_df.head(20))  # แสดงคู่แรก 20 คู่เพื่อการตรวจสอบ

# จับคู่ loc1 ใน data_1 กับ location_l ใน data_2 เพื่อหา neighborhood_9 และสร้างคอลัมน์ neighbor
merged_data = pd.merge(data_1, location_neighborhood_df, left_on='loc1', right_on='location_l', how='left')

# เปลี่ยนชื่อคอลัมน์ neighborhood_9 เป็น neighbor
merged_data = merged_data.rename(columns={'neighborhood_9': 'neighbor'})

# ลบคอลัมน์ location_l ที่เกินมา
merged_data = merged_data.drop(columns=['location_l'])

# บันทึกข้อมูลที่อัปเดตลงในไฟล์ CSV ใหม่
output_file_path = 'data/updated_data_with_neighbor.csv'
merged_data.to_csv(output_file_path, index=False)

# แสดงข้อมูลแถวแรกๆ เพื่อการตรวจสอบการจับคู่
print("แถวแรกของข้อมูลที่อัปเดต:")
print(merged_data[['loc1', 'neighbor']].head())

คู่ที่ไม่ซ้ำของ location_l และ neighborhood_9 จาก data_2:
           location_l neighborhood_9
0              Kisumu     Kawangware
1            Manyatta     Kawangware
2          Kawangware     Kawangware
3              Oyugis     Kawangware
4              Kisumu         Kayole
5              London         Kayole
6           Lolgorien         Kayole
7            Londiani         Kayole
8              Kayole         Kayole
9                 NaN         Kayole
10             Kedowa         Kayole
11            Pumwani     Kawangware
12            Kericho     Kawangware
13            Makueni     Kawangware
14           Machakos     Kawangware
15              Moshi     Kawangware
16  Muslim Kawangware     Kawangware
17              Congo     Kawangware
18            Manyara     Kawangware
19             Awendo     Kawangware
แถวแรกของข้อมูลที่อัปเดต:
       loc1       neighbor
0  Machakos     Kawangware
1  Machakos         Kayole
2  Machakos  Ongata Rongai
3  Machakos     Kawangware
4  Machakos         Kayole

In [58]:
import pandas as pd

# Load the CSV file
df = pd.read_csv('data/star_all_distances.csv')

# Specify the column names
column_name1 = 'city_8'
column_name2 = 'neighborhood_9'
column_name3 = 'location_l'

# Get the unique values for each column
unique_values_column1 = df[column_name1].unique()
unique_values_column2 = df[column_name2].unique()
unique_values_column3 = df[column_name3].unique()

# Print the unique values for each column
# print(f"Unique values in {column_name1}: {unique_values_column1}")
# print(f"Unique values in {column_name2}: {unique_values_column2}")

# If you want to find unique pairs of values from both columns
unique_pairs = df[[column_name1,column_name3, column_name2]].drop_duplicates()

# Print the unique pairs
print(f"Unique pairs of {column_name1} and {column_name2}:\n{unique_pairs}")

Unique pairs of city_8 and neighborhood_9:
             city_8   location_l neighborhood_9
0           Nairobi       Kisumu     Kawangware
1           Nairobi     Manyatta     Kawangware
2           Nairobi   Kawangware     Kawangware
4           Nairobi       Oyugis     Kawangware
8           Nairobi       Kisumu         Kayole
...             ...          ...            ...
19868  Johannesburg    Tweelagte          Berea
19869  Johannesburg      Devland          Berea
19875  Johannesburg      Quthing          Berea
19907  Johannesburg     Meyerton          Berea
19911  Johannesburg  Forest Town          Berea

[3358 rows x 3 columns]

In [66]:
import pandas as pd

# Load the CSV file
df = pd.read_csv('data/star_all_distances.csv')

# Specify the column names
column_name1 = 'city_8'
column_name2 = 'neighborhood_9'
column_name3 = 'location_l'

# Get the unique values for each column
unique_values_column1 = df[column_name1].unique()
unique_values_column2 = df[column_name2].unique()

# Print the unique values for each column
# print(f"Unique values in {column_name1}: {unique_values_column1}")
# print(f"Unique values in {column_name2}: {unique_values_column2}")

# If you want to find unique pairs of values from both columns
unique_pairs = df[[column_name1, column_name2]].drop_duplicates()

# Print the unique pairs
print(f"Unique pairs of {column_name1} and {column_name2}:\n{unique_pairs}")

Unique pairs of city_8 and neighborhood_9:
            city_8 neighborhood_9
0          Nairobi     Kawangware
8          Nairobi         Kayole
74           Accra         Madina
289   Johannesburg          Berea
316        Nairobi             -3
731   Johannesburg     Katlehong
1050         Accra     Old Fadama
1079         Accra     James Town
1604       Nairobi  Ongata Rongai
2996  Johannesburg      Diepsloot

In [70]:
import pandas as pd

# Load the CSV files
df_star = pd.read_csv('data/star_all_distances.csv')
df_origin = pd.read_csv('data/origin_migrations_UR.csv')

unique_pairs_star = df_star[['city_8', 'location_l']].drop_duplicates()
unique_pairs_origin = df_origin[['city_8', 'loc2']].drop_duplicates()

print("Unique pairs of city_8 and location_l in star_all_distances.csv:")
print(unique_pairs_star)

print("Unique pairs of city_8 and loc2 in origin_migrations_UR.csv:")
print(unique_pairs_origin)

# คุณสามารถแก้ไขค่าที่ไม่ตรงกันได้ด้วยการสร้าง mapping ที่ถูกต้อง
# สมมุติว่าเราพบว่ามีข้อผิดพลาดและต้องการแก้ไขบางค่าใน df_star
# ตัวอย่างการแก้ไขข้อมูลใน df_star:
# df_star.loc[df_star['neighborhood_9'] == 'Kawangware', 'city_8'] = 'Nairobi'
# df_star.loc[df_star['neighborhood_9'] == 'Kayole', 'city_8'] = 'Nairobi'
# (ทำซ้ำสำหรับคู่ค่าที่ต้องการแก้ไข)

# หลังจากแก้ไขแล้ว สร้าง mapping จาก location_l ไปยัง neighborhood_9
location_to_neighborhood = df_star.set_index('location_l')['neighborhood_9'].to_dict()

# Map the loc2 values to their corresponding neighborhood_9 values
df_origin['neighborhood_9'] = df_origin['loc2'].map(location_to_neighborhood)

# Print the updated dataframe
print(df_origin)

# Save the updated dataframe to a new CSV file
df_origin.to_csv('data/origin_migrations_with_neighborhood.csv', index=False)

Unique pairs of city_8 and location_l in star_all_distances.csv:
             city_8   location_l
0           Nairobi       Kisumu
1           Nairobi     Manyatta
2           Nairobi   Kawangware
4           Nairobi       Oyugis
9           Nairobi       London
...             ...          ...
19831  Johannesburg       Kigoma
19832  Johannesburg   North West
19869  Johannesburg      Devland
19875  Johannesburg      Quthing
19911  Johannesburg  Forest Town

[2503 rows x 2 columns]
Unique pairs of city_8 and loc2 in origin_migrations_UR.csv:
      city_8        loc2
0    Nairobi       Kisii
2    Nairobi      Kisumu
4    Nairobi    Machakos
6    Nairobi       Uvira
8    Nairobi       Siaya
..       ...         ...
680    Accra         Asa
684    Accra     Dadieso
686    Accra         Leo
688    Accra        Orlu
690    Accra  Porto-Novo

[309 rows x 2 columns]
     Unnamed: 0.1  Unnamed: 0   city_8                           location  \
0               0           0  Nairobi        ('Kisii', 'Kisii', 'Kenya')
1               1           1  Nairobi        ('Kisii', 'Kisii', 'Kenya')
2               2           2  Nairobi      ('Kisumu', 'Kisumu', 'Kenya')
3               3           3  Nairobi      ('Kisumu', 'Kisumu', 'Kenya')
4               4           4  Nairobi  ('Machakos', 'Machakos', 'Kenya')
..            ...         ...      ...                                ...
687           687         687    Accra     ('nan', 'Leo', 'Burkina Faso')
688           688         688    Accra         ('nan', 'Orlu', 'Nigeria')
689           689         689    Accra         ('nan', 'Orlu', 'Nigeria')
690           690         690    Accra     ('nan', 'Porto-Novo', 'Benin')
691           691         691    Accra     ('nan', 'Porto-Novo', 'Benin')

     num_moves        dist   azimuth        lat        lon  \
0           15    0.010000  0.000000  36.820443  -1.292567
1           15  226.955417  2.922134  34.753986  -0.738943
2           13    0.010000  0.000000  36.820443  -1.292567
3           13  245.805142  2.688263  34.754176  -0.102911
4           10    0.010000  0.000000  36.820443  -1.292567
..         ...         ...       ...        ...        ...
687          1  648.430424  1.910416  -2.117445  11.181410
688          1    0.010000  0.000000  -0.187971   5.591177
689          1  797.262669  0.018260   7.040932   5.817910
690          1    0.010000  0.000000  -0.187971   5.591177
691          1  321.806370  0.284736   2.625336   6.499072

                                      location_pair  ...  Non-Urban City  \
0          ('Nairobi', ('Kisii', 'Kisii', 'Kenya'))  ...             0.0
1          ('Nairobi', ('Kisii', 'Kisii', 'Kenya'))  ...             0.0
2        ('Nairobi', ('Kisumu', 'Kisumu', 'Kenya'))  ...             0.0
3        ('Nairobi', ('Kisumu', 'Kisumu', 'Kenya'))  ...             0.0
4    ('Nairobi', ('Machakos', 'Machakos', 'Kenya'))  ...             0.0
..                                              ...  ...             ...
687       ('Accra', ('nan', 'Leo', 'Burkina Faso'))  ...             0.0
688           ('Accra', ('nan', 'Orlu', 'Nigeria'))  ...             0.0
689           ('Accra', ('nan', 'Orlu', 'Nigeria'))  ...             0.0
690       ('Accra', ('nan', 'Porto-Novo', 'Benin'))  ...             0.0
691       ('Accra', ('nan', 'Porto-Novo', 'Benin'))  ...             0.0

    Non-Urban Town Non-Urban Village Unclassified City Unclassified Town  \
0              0.0               0.0               0.0               0.0
1              0.0               0.0               0.0               0.0
2              0.0               0.0               0.0               0.0
3              0.0               0.0               0.0               0.0
4              0.0               0.0               0.0               0.0
..             ...               ...               ...               ...
687            1.0               0.0               0.0               0.0
688            0.0               0.0               0.0               0.0
689            0.0               0.0               0.0               0.0
690            0.0               0.0               0.0               0.0
691            0.0               0.0               0.0               0.0

    Unclassified Village Urban City Urban Town Urban Village  neighborhood_9
0                    0.0        0.0        2.0          16.0   Ongata Rongai
1                    0.0        0.0        2.0          16.0   Ongata Rongai
2                    0.0        0.0        7.0          24.0   Ongata Rongai
3                    0.0        0.0        7.0          24.0   Ongata Rongai
4                    0.0        0.0        2.0          16.0   Ongata Rongai
..                   ...        ...        ...           ...             ...
687                  0.0        0.0        0.0           0.0          Madina
688                  0.0        0.0        1.0           0.0          Madina
689                  0.0        0.0        1.0           0.0          Madina
690                  0.0        1.0        0.0           0.0          Madina
691                  0.0        1.0        0.0           0.0          Madina

[692 rows x 30 columns]

In [61]:
import pandas as pd

# Load the CSV file
df = pd.read_csv('data/star_all_distances.csv')

# Specify the column names
column_name1 = 'city_8'
column_name2 = 'neighborhood_9'
column_name3 = 'location_l'

# Get the unique values for each column
unique_values_column1 = df[column_name1].unique()
unique_values_column2 = df[column_name2].unique()
unique_values_column3 = df[column_name3].unique()

# Print the unique values for each column
# print(f"Unique values in {column_name1}: {unique_values_column1}")
# print(f"Unique values in {column_name2}: {unique_values_column2}")

# If you want to find unique pairs of values from both columns
unique_pairs = df[[column_name1,column_name3, column_name2]].drop_duplicates()

# Print the unique pairs
print(f"Unique pairs of {column_name1} and {column_name2}:\n{unique_pairs}")

Unique pairs of city_8 and loc2:
      city_8        loc2
0    Nairobi       Kisii
2    Nairobi      Kisumu
4    Nairobi    Machakos
6    Nairobi       Uvira
8    Nairobi       Siaya
..       ...         ...
680    Accra         Asa
684    Accra     Dadieso
686    Accra         Leo
688    Accra        Orlu
690    Accra  Porto-Novo

[309 rows x 2 columns]

In [65]:
import pandas as pd

# Load the CSV files
df_star = pd.read_csv('data/star_all_distances.csv')
df_origin = pd.read_csv('data/origin_migrations_UR.csv')

# Specify the column names
column_location_l = 'location_l'
column_loc2 = 'loc2'
column_neighborhood = 'neighborhood_9'

# Create a mapping from location_l to neighborhood_9
location_to_neighborhood = df_star.set_index(column_location_l)[column_neighborhood].to_dict()

# Map the loc2 values to their corresponding neighborhood_9 values
df_origin[column_neighborhood] = df_origin[column_loc2].map(location_to_neighborhood)

# Print the updated dataframe
print(df_origin)

# Save the updated dataframe to a new CSV file
df_origin.to_csv('data/new.csv', index=False)

     Unnamed: 0.1  Unnamed: 0   city_8                           location  \
0               0           0  Nairobi        ('Kisii', 'Kisii', 'Kenya')
1               1           1  Nairobi        ('Kisii', 'Kisii', 'Kenya')
2               2           2  Nairobi      ('Kisumu', 'Kisumu', 'Kenya')
3               3           3  Nairobi      ('Kisumu', 'Kisumu', 'Kenya')
4               4           4  Nairobi  ('Machakos', 'Machakos', 'Kenya')
..            ...         ...      ...                                ...
687           687         687    Accra     ('nan', 'Leo', 'Burkina Faso')
688           688         688    Accra         ('nan', 'Orlu', 'Nigeria')
689           689         689    Accra         ('nan', 'Orlu', 'Nigeria')
690           690         690    Accra     ('nan', 'Porto-Novo', 'Benin')
691           691         691    Accra     ('nan', 'Porto-Novo', 'Benin')

     num_moves        dist   azimuth        lat        lon  \
0           15    0.010000  0.000000  36.820443  -1.292567
1           15  226.955417  2.922134  34.753986  -0.738943
2           13    0.010000  0.000000  36.820443  -1.292567
3           13  245.805142  2.688263  34.754176  -0.102911
4           10    0.010000  0.000000  36.820443  -1.292567
..         ...         ...       ...        ...        ...
687          1  648.430424  1.910416  -2.117445  11.181410
688          1    0.010000  0.000000  -0.187971   5.591177
689          1  797.262669  0.018260   7.040932   5.817910
690          1    0.010000  0.000000  -0.187971   5.591177
691          1  321.806370  0.284736   2.625336   6.499072

                                      location_pair  ...  Non-Urban City  \
0          ('Nairobi', ('Kisii', 'Kisii', 'Kenya'))  ...             0.0
1          ('Nairobi', ('Kisii', 'Kisii', 'Kenya'))  ...             0.0
2        ('Nairobi', ('Kisumu', 'Kisumu', 'Kenya'))  ...             0.0
3        ('Nairobi', ('Kisumu', 'Kisumu', 'Kenya'))  ...             0.0
4    ('Nairobi', ('Machakos', 'Machakos', 'Kenya'))  ...             0.0
..                                              ...  ...             ...
687       ('Accra', ('nan', 'Leo', 'Burkina Faso'))  ...             0.0
688           ('Accra', ('nan', 'Orlu', 'Nigeria'))  ...             0.0
689           ('Accra', ('nan', 'Orlu', 'Nigeria'))  ...             0.0
690       ('Accra', ('nan', 'Porto-Novo', 'Benin'))  ...             0.0
691       ('Accra', ('nan', 'Porto-Novo', 'Benin'))  ...             0.0

    Non-Urban Town Non-Urban Village Unclassified City Unclassified Town  \
0              0.0               0.0               0.0               0.0
1              0.0               0.0               0.0               0.0
2              0.0               0.0               0.0               0.0
3              0.0               0.0               0.0               0.0
4              0.0               0.0               0.0               0.0
..             ...               ...               ...               ...
687            1.0               0.0               0.0               0.0
688            0.0               0.0               0.0               0.0
689            0.0               0.0               0.0               0.0
690            0.0               0.0               0.0               0.0
691            0.0               0.0               0.0               0.0

    Unclassified Village Urban City Urban Town Urban Village  neighborhood_9
0                    0.0        0.0        2.0          16.0   Ongata Rongai
1                    0.0        0.0        2.0          16.0   Ongata Rongai
2                    0.0        0.0        7.0          24.0   Ongata Rongai
3                    0.0        0.0        7.0          24.0   Ongata Rongai
4                    0.0        0.0        2.0          16.0   Ongata Rongai
..                   ...        ...        ...           ...             ...
687                  0.0        0.0        0.0           0.0          Madina
688                  0.0        0.0        1.0           0.0          Madina
689                  0.0        0.0        1.0           0.0          Madina
690                  0.0        1.0        0.0           0.0          Madina
691                  0.0        1.0        0.0           0.0          Madina

[692 rows x 30 columns]